services:
  # Service Registry (Eureka)
  service-registry:
    build: ./ServiceRegistry
    container_name: service-registry
    ports:
      - "8761:8761"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      retries: 10
      start_period: 15s

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:4.1.4-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 30s

  # API Gateway
  api-gateway:
    build: ./ApiGateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      service-registry:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-registry:8761/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    restart: unless-stopped

  # Auth Service
  auth-service:
    build: ./AuthService
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      service-registry:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./AuthService/.env
    restart: unless-stopped

  # Inventory Service
  inventory-service:
    build: ./InventoryService
    container_name: inventory-service
    ports:
      - "8082:8082"
    depends_on:
      service-registry:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./InventoryService/.env
    restart: unless-stopped

  # Order Service
  order-service:
    build: ./OrderService
    container_name: order-service
    ports:
      - "8083:8083"
    depends_on:
      service-registry:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./OrderService/.env
    restart: unless-stopped

  # Supplier Service
  supplier-service:
    build: ./SupplierService
    container_name: Supplier-service
    ports:
      - "8084:8084"
    depends_on:
      service-registry:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./SupplierService/.env
    restart: unless-stopped

volumes:
  rabbitmq_data:
