spring:
  application:
    name: product-service

server:
  port: 8084

eureka:
  client:
    service-url:
#      defaultZone: http://service-registry:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true