spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true   # or false
              lower-case-service-id: true

server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
