spring:
  application:
    name: EUREKA-SERVER

server:
  port: 8761

eureka:
  server:
    enable-self-preservation: true
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"


management:
  endpoints:
    web:
      exposure:
        include: health,info