spring:
  application:
    name: order-service

server:
  port: 8083

eureka:
  client:
    service-url:
#      defaultZone: http://service-registry:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true